title: Road to Glory FFL
description: The official league headquarters for Road to Glory Fantasy Football.
theme: minima
url: "https://stringer56.github.io"
baseurl: "/fantasy-football-site"
lang: en
timezone: America/New_York
collections:
  franchises:
    output: true
    permalink: /teams/:slug/
  seasons:
    output: true
    permalink: /history/:name/
defaults:
  - scope:
      path: ""
      type: franchises
    values:
      layout: franchise
  - scope:
      path: ""
      type: seasons
    values:
      layout: season
