title: Road to Glory FFL
description: League hub powered by Yahoo Fantasy API via GitHub Actions
theme: minima
url: "https://stringer56.github.io"
baseurl: "/fantasy-football-site"   # 👈 project repo path
